### PR TITLE
Make compatible with Windows.

### PR DESCRIPTION
**Pull request by qkevinto**
Replace back slashes with forward slashes if path.sep is '\'.

### CODE REVIEW

**Comment by tiye** [comment]
I don't have a window device to test. But I'm glad to update the npm package if you need.
Actually this package is no longer used in our production since I switched to https://github.com/mvc-works/pages-rev (not stable though) instead.

**Comment by qkevinto** [comment]
If you think it will benefit others using the package then please do update the npm package, that would be great and much appreciated!

I just figured I'd make a pull request after running into problems getting it to work on a Windows environment – `path.sep` on Windows is `\`, which outputs paths like `assets\scripts\main.js` and when used in `parts = contents.split(short)`, it doesn't match `assets/scripts/main.js` in `contents`.

**Comment by tiye** [comment]
`0.0.4` published, hope it helps, https://www.npmjs.com/package/gulp-rev-manifest-replace

**Comment by qkevinto** [comment]
Cheers! :)

**Pull request merged**
